name: Build and Test

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  test-build:
    runs-on: ubuntu-latest
    container: debian:trixie

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        apt update
        apt install -y libssl-dev libbsd-dev python3-dev build-essential devscripts debhelper
        apt install -y debhelper dh-python pybuild-plugin-pyproject python3-pytest python3-all-dev
        apt install -y python3-pip python3-setuptools python3-build libidn-dev

    - name: Test Debian package build
      run: |
        dpkg-buildpackage -us -uc -b

    - name: Install and test packages
      run: |
        dpkg -i ../libtruenas-scram1_*.deb
        dpkg -i ../libtruenas-scram-dev_*.deb
        dpkg -i ../python3-truenas-scram_*.deb
        python3 -m pytest tests/ -v

